database:
  cassandra:
    host: cassandra
    port: 
      local: 29042
      docker: 9042
    contact_points:
      local: ["127.0.0.1"]
      docker: ["cassandra"]
    username: cassandra
    keyspace: recommender
    session_name: recommender
    tables:
      users: users
      jobs: job_listings
      search: search_metadata
      clicks: clicks_metadata

  chroma:
    host: 
      local: "localhost"
      docker: "chroma"
    port: 
      local: "8500"
      docker: "8000"
    username: "admin"
    collection: "jobs"

selenium:
  profile_path:
    local: /home/abraham-pc/snap/firefox/common/.mozilla/firefox/
    docker: /root/.mozilla/firefox/

deployment: True