database:
  cassandra:
    host: cassandra
    port: 29042
    username: cassandra
    keyspace: recommender
    session_name: recommender
    tables:
      users: users
      jobs: job_listings
      search: search_metadata
      clicks: clicks_metadata

  chroma:
    host: "localhost"
    port: "8500"
    username: "admin"
    collection: "jobs"

selenium:
  profile_path:
    local: /home/abraham-pc/snap/firefox/common/.mozilla/firefox/
    docker: /root/.mozilla/firefox/

deployment: False