server:
  local: http://localhost:28000
  docker: http://backend:28000

admin:
  username: admin
  password: admin
  hash: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918

deployment: True